import pickle
import pandas as pd
import tgt
import chardet

def predict_encoding(tg_path):
    '''Predict a file's encoding using chardet'''
    # Open the file as binary data
    with open(tg_path, 'rb') as f:
        # Join binary lines for specified number of lines
        rawdata = b''.join(f.readlines())
    return chardet.detect(rawdata)['encoding']

features = ['f0_avgutt_diff','p_dur','n_dur','e_range','e_maxavg_diff',
            'e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff']

scaler = pickle.load(open('scaler.prosodic.pkl', 'rb'))
chosen_model = pickle.load(open('SVC_model.pkl', 'rb')) # ADAPT MODEL AFTER TALKING WITH SANDRA

# Adapt here according to the name and path of your csv file
df_prosodic = pd.read_csv('AL1_prosodic_features.csv')
# Adapt here according to the path of your file generated by ufpalign
tg_phone_path = "MuPe-Diversidades/versao-1/AL/"
# Adapt here according to the name of your file generated by ufpalign
tg_phone_filename = "AL1_fones"

tg_phone = tgt.io.read_textgrid(tg_phone_path+tg_phone_filename+".TextGrid", predict_encoding(tg_phone_path+tg_phone_filename+".TextGrid"), include_empty_intervals=False)
final_tg_name = tg_phone_filename + "_prosodic_segmented.Textgrid"

X = df_prosodic[features]        
X = df_prosodic[features].fillna(0) # Replace NaN values with 0 in X
X = scaler.fit_transform(X)

# Predicting boundaries
predicted_labels = chosen_model.predict(X)  

# Generating textgrid according to predicted boundaries
predicted_syllables = df_prosodic['frame']

syllables_tier = tg_phone.get_tier_by_name("silabas-fonemas")
phrase_phonemes_tier = tg_phone.get_tier_by_name("frase-fonemas")
phrase_graphemes_tier = tg_phone.get_tier_by_name("frase-grafemas")
syllables_tier = [syllable for syllable in syllables_tier if syllable.text != "sil"] # removing silences

final_textgrid = tgt.core.TextGrid()
new_tier = tgt.core.IntervalTier(start_time=0, end_time=predicted_syllables[len(predicted_syllables)-1].split('_')[3], name="Prosodic Segmented Utterances", objects=None)

phrase_phonemes_list = phrase_phonemes_tier[0].text.split()
phrase_graphemes_list = phrase_graphemes_tier[0].text.split()

i = 0
interval_start_time = 0
interval_text = ""
words_list_index = 0
current_word = ""

if(len(syllables_tier) != len(predicted_syllables)):
    print("Quantity of syllables of the csv file and quantity of syllables of phonemes textgrid file are different. Can't continue. Killing program.")
    print("Len syllables tier:", len(syllables_tier))
    print("Len predicted syllables:", len(predicted_syllables))
    quit()

for i in range(len(predicted_syllables)):

    csv_syllable_text = predicted_syllables[i].split('_')[1]

    # Adiciono a sílaba atual
    current_word += csv_syllable_text
    
    # Comparo com a camada de 
    if current_word == phrase_phonemes_list[words_list_index]:
        if interval_text != "":
            interval_text += " "
        interval_text += phrase_graphemes_list[words_list_index]
        words_list_index += 1
        current_word = ""
    else: # SERIA O IDEAL - VER COM SANDRA SE A GENTE COLOCA ESSA BARREIRA DE NUNCA SEGMENTAR NO MEIO DE PALAVRAS, OU SE A GENTE SEGMENTA IGUALZINHO O ALGORITMO DE ML QUER
        if predicted_labels[i] == 'TB':
            print("Algoritmo previu uma fronteira no meio de uma palavra, estou barrando e seguindo sem marcá-la")
        continue

    if predicted_labels[i] == 'TB' or i == len(predicted_syllables)-1:
        csv_syllable_end_time = float(predicted_syllables[i].split('_')[3])
        new_interval = tgt.core.Interval(start_time=interval_start_time,end_time=csv_syllable_end_time, text=interval_text) # Here, should I write "sil" instead?
        new_tier.add_interval(new_interval)
        
        # checking if we need a silence interval after the current interval
        if i+1 < len(predicted_syllables) and csv_syllable_end_time != float(predicted_syllables[i+1].split('_')[2]):
            new_interval = tgt.core.Interval(start_time=csv_syllable_end_time,end_time=float(predicted_syllables[i+1].split('_')[2]), text="") # Here, should I write "sil" instead?
            new_tier.add_interval(new_interval)
            interval_start_time = float(predicted_syllables[i+1].split('_')[2])
        else:
            interval_start_time = csv_syllable_end_time
        interval_text = ""
        
    elif predicted_labels[i] == 'NB':
        continue
    else:
        print("ERROR, NO LABEL WAS ASSIGNED TO CURRENT SYLLABLE, ENDING PROGRAM")
        quit()
    
final_textgrid.add_tier(new_tier)
tgt.io.write_to_file(final_textgrid, final_tg_name, format='long', encoding='utf-8') 

print("\nTextgrid with prosodic segmented utterances generated successfully!")
print("It can be found in the same folder of this code with the name:",final_tg_name)