import pickle
import pandas as pd
import tgt
import chardet
import sys

def predict_encoding(tg_path):
    '''Predict a file's encoding using chardet'''
    # Open the file as binary data
    with open(tg_path, 'rb') as f:
        # Join binary lines for specified number of lines
        rawdata = b''.join(f.readlines())
    return chardet.detect(rawdata)['encoding']

if len(sys.argv) < 3:
    print("Missing audio or textgrid filenames, please write them like this when you run the code: python3 mycode.py myfeatures.csv mytextgrid.TextGrid")
    sys.exit(1)
  # Adapt here according to the path of your audio and textgrid generated by ufpalign
csv_path = sys.argv[1] # 'AL1_prosodic_features.csv' non filtered
tg_phone = sys.argv[2] #"AL1_fones.TextGrid"


# OBSOLETE - DELETE BELOW AFTERWARDS
#scaler = pickle.load(open('scaler_prosodic.pkl', 'rb')) 
#scaler = pickle.load(open('scaler_prosodic_newufpalignversion_articleversion_9features_trainset.pkl', 'rb'))
#scaler = pickle.load(open('scaler_prosodic_all_mupe-diversidades.pkl', 'rb'))
# Comment models that you will not use
#chosen_model = pickle.load(open('RandomForest_model.pkl', 'rb')) 
#chosen_model = pickle.load(open('RandomForest_model_newufpalignversion_articleversion_9features_trainset.pkl', 'rb')) 
#chosen_model = pickle.load(open('RandomForest_model_all_mupe-diversidades.pkl', 'rb')) 
# OBSOLETE - DELETE ABOVE AFTERWARDS

# CHOOSE VERSION OF MODEL YOU WISH TO USE AND COMMENT THE OTHER TWO BLOCKS

# 8 FEATURES OLD UFPALIGN
#features = ['p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] # WITHOUT F0 AVG UTT DIFF
#scaler = pickle.load(open('scaler_all_mupe-diversidades_8features.pkl', 'rb'))
#chosen_model = pickle.load(open('RF_all_mupe-diversidades_8features.pkl', 'rb')) 
#final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_8features.Textgrid"

# 8 FEATURES NEW UFPALIGN FILTERED
#features = ['p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] # WITHOUT F0 AVG UTT DIFF
#scaler = pickle.load(open('scaler_all_mupe-diversidades_8features_newufpalign.pkl', 'rb'))
#chosen_model = pickle.load(open('RF_all_mupe-diversidades_8features_newufpalign.pkl', 'rb')) 
#final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_8features_newufpalign.Textgrid"

# 8 FEATURES NEW UFPALIGN NON-FILTERED
features = ['p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] # WITHOUT F0 AVG UTT DIFF
scaler = pickle.load(open('scaler_all_mupe-diversidades_8features_newufpalign_non-filtered.pkl', 'rb'))
chosen_model = pickle.load(open('RF_all_mupe-diversidades_8features_newufpalign_non-filtered.pkl', 'rb')) 
final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_8features_newufpalign_non-filtered.Textgrid"

# 9 FEATURES ORIGINAL F0_AVGUTT_DIFF
#features = ['f0_avgutt_diff','p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] 
#scaler = pickle.load(open('scaler_prosodic_only-trainset_mupe-diversidades_9features_originalf0_avg_utt_diff.pkl', 'rb'))
#chosen_model = pickle.load(open('RF_only-trainset_mupe-diversidades_9features_originalf0_avg_utt_diff.pkl', 'rb')) 
#final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_9featuresoriginal.Textgrid"

# 9 FEATURES NEW VERSION OF FO_AVGUTT_DIFF: F0_AVGUTT_DIFF_2
#features = ['f0_avgutt_diff_2','p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] 
#scaler = pickle.load(open('scaler_prosodic_all_mupe-diversidades_9features_new-f0_avg_utt_diff_2.pkl', 'rb'))
#chosen_model = pickle.load(open('RF_all_mupe-diversidades_9features_new-f0_avg_utt_diff_2.pkl', 'rb')) # _midwordcutadjusted
#final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_9newfeature.Textgrid"

print(csv_path, tg_phone, final_tg_name)

df_prosodic = pd.read_csv(csv_path)
tg_phone = tgt.io.read_textgrid(tg_phone, predict_encoding(tg_phone), include_empty_intervals=False)

X = df_prosodic[features]        
X = df_prosodic[features].fillna(0) # Replace NaN values with 0 in X
X = scaler.fit_transform(X)

# Predicting boundaries
predicted_labels = chosen_model.predict(X)  

# Generating textgrid according to predicted boundaries
predicted_syllables = df_prosodic['frame']

syllables_tier = tg_phone.get_tier_by_name("silabas-fonemas")
phrase_phonemes_tier = tg_phone.get_tier_by_name("frase-fonemas")
phrase_graphemes_tier = tg_phone.get_tier_by_name("frase-grafemas")
syllables_tier = [syllable for syllable in syllables_tier if syllable.text != "sil"] # removing silences

final_textgrid = tgt.core.TextGrid()
new_tier = tgt.core.IntervalTier(start_time=0, end_time=predicted_syllables[len(predicted_syllables)-1].split('_')[3], name="Prosodic Segmented Utterances", objects=None)

phrase_phonemes_list = phrase_phonemes_tier[0].text.split()
phrase_graphemes_list = phrase_graphemes_tier[0].text.split()

# CONDITION TO ENSURE WE WON'T HAVE THE CONCATENATION PROBLEM
joined_phrase_phonemes_list = ''.join(phrase_phonemes_list)
joined_csv_syllables = ""
for syllable in predicted_syllables:
    joined_csv_syllables += syllable.split('_')[1]

if joined_phrase_phonemes_list != joined_csv_syllables:
    print("ERROR! Syllables contained in the extracted features file and in the phones textgrid syllables tier are different. Killing program.")
    quit()

i = 0
midword_tb_guess_counter = 0
interval_start_time = 0
interval_text = ""
words_list_index = 0
current_word = ""

if(len(syllables_tier) != len(predicted_syllables)):
    print("Quantity of syllables of the csv file and quantity of syllables of phonemes textgrid file are different. Can't continue. Killing program.")
    print("Len syllables tier:", len(syllables_tier))
    print("Len predicted syllables:", len(predicted_syllables))
    quit()

#for i in range(len(predicted_syllables)):
while i < len(predicted_syllables):

    csv_syllable_text = predicted_syllables[i].split('_')[1]

    # Adiciono a sílaba atual
    current_word += csv_syllable_text
    
    # Comparo com a camada de 
    if current_word == phrase_phonemes_list[words_list_index]:
        if interval_text != "":
            interval_text += " "
        interval_text += phrase_graphemes_list[words_list_index]
        words_list_index += 1
        current_word = ""
    else:
        if predicted_labels[i] == 'TB':
            print("\nAlgoritmo previu uma fronteira no meio de uma palavra, estou inserindo uma fronteira no fim dessa palavra")
            print("Isto ocorreu na seguinte palavra:", phrase_phonemes_list[words_list_index], " - ", current_word, " - sílaba atual: ", csv_syllable_text, " - ", predicted_syllables[i])
            if i+1 < len(predicted_syllables):
                print("próxima sílaba: ", predicted_syllables[i+1], " - ", predicted_syllables[i+1].split('_')[1])
            midword_tb_guess_counter +=1
            
            while current_word != phrase_phonemes_list[words_list_index] and i+1 < len(predicted_syllables):
                print("DEBUG: ", i, predicted_syllables[i], current_word)
                i += 1
                csv_syllable_text = predicted_syllables[i].split('_')[1]
                current_word += csv_syllable_text
            print("DEBUG: ", i, predicted_syllables[i], current_word, phrase_phonemes_list[words_list_index], predicted_labels[i])
        
            predicted_labels[i] = 'TB'
            print(predicted_labels[i])
            if interval_text != "":
                interval_text += " "
            interval_text += phrase_graphemes_list[words_list_index]
            words_list_index += 1
            current_word = ""
    
    if predicted_labels[i] == 'TB' or i == len(predicted_syllables)-1:
        csv_syllable_end_time = float(predicted_syllables[i].split('_')[3])
        new_interval = tgt.core.Interval(start_time=interval_start_time,end_time=csv_syllable_end_time, text=interval_text) # Here, should I write "sil" instead?
        new_tier.add_interval(new_interval)
        
        # checking if we need a silence interval after the current interval
        if i+1 < len(predicted_syllables) and csv_syllable_end_time != float(predicted_syllables[i+1].split('_')[2]):
            new_interval = tgt.core.Interval(start_time=csv_syllable_end_time,end_time=float(predicted_syllables[i+1].split('_')[2]), text="") # Here, should I write "sil" instead?
            new_tier.add_interval(new_interval)
            interval_start_time = float(predicted_syllables[i+1].split('_')[2])
        else:
            interval_start_time = csv_syllable_end_time
        interval_text = ""
        
    elif predicted_labels[i] == 'NB':
        i += 1
        continue
    else:
        print("\nERROR, NO LABEL WAS ASSIGNED TO CURRENT SYLLABLE, ENDING PROGRAM\n")
        quit()
    i += 1
    
final_textgrid.add_tier(new_tier)
tgt.io.write_to_file(final_textgrid, final_tg_name, format='long', encoding='utf-8') 

print("\nTextgrid with prosodic segmented utterances generated successfully!\n")
print("The classifier tried to mark TBs in the middle of ", midword_tb_guess_counter," words (but we did not insert those boundaries as we understand that TBs should not cut words in half)")
print("\nIt can be found in the same folder of this code with the name:",final_tg_name, "\n")