import pickle
import pandas as pd
import tgt
import chardet
import sys

def predict_encoding(tg_path):
    '''Predict a file's encoding using chardet'''
    # Open the file as binary data
    with open(tg_path, 'rb') as f:
        # Join binary lines for specified number of lines
        rawdata = b''.join(f.readlines())
    return chardet.detect(rawdata)['encoding']

# 8 FEATURES
#features = ['p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] # WITHOUT F0 AVG UTT DIFF
# 9 FEATURES
features = ['f0_avgutt_diff','p_dur','n_dur','e_range','e_maxavg_diff','e_avgmin_diff','f0_range','f0_maxavg_diff','f0_avgmin_diff'] # we decided to remove this feature since we needed to know TB boundaries to measure f0 avg of an utterance

scaler = pickle.load(open('scaler_prosodic.pkl', 'rb'))
#scaler = pickle.load(open('scaler_prosodic_newufpalignversion_articleversion_9features_trainset.pkl', 'rb'))
#scaler = pickle.load(open('scaler_prosodic_all_mupe-diversidades.pkl', 'rb'))

# Comment models that you will not use
chosen_model = pickle.load(open('RandomForest_model.pkl', 'rb')) 
#chosen_model = pickle.load(open('RandomForest_model_newufpalignversion_articleversion_9features_trainset.pkl', 'rb')) 
#chosen_model = pickle.load(open('RandomForest_model_all_mupe-diversidades.pkl', 'rb')) 

if len(sys.argv) < 3:
    print("Missing audio or textgrid filenames, please write them like this when you run the code: python3 mycode.py myfeatures.csv mytextgrid.TextGrid")
    sys.exit(1)
  # Adapt here according to the path of your audio and textgrid generated by ufpalign
csv_path = sys.argv[1] # 'AL1_prosodic_features.csv'
tg_phone = sys.argv[2] #"AL1_fones.TextGrid"
final_tg_name = csv_path.split('.')[0] + "_prosodic_segmented_colored1.Textgrid"

print(csv_path, tg_phone, final_tg_name)

df_prosodic = pd.read_csv(csv_path)
tg_phone = tgt.io.read_textgrid(tg_phone, predict_encoding(tg_phone), include_empty_intervals=False)

X = df_prosodic[features]        
X = df_prosodic[features].fillna(0) # Replace NaN values with 0 in X
X = scaler.fit_transform(X)

# GETTING THE REFERENCE TEXTGRID
if len(sys.argv) > 3:
    tg_reference = sys.argv[3]
    tg_reference = tgt.io.read_textgrid(tg_reference, predict_encoding(tg_reference), include_empty_intervals=False)

# GETTING THE SET FROM EACH SYLLABLE
#df_complete_mupe_diversidades = pd.read_csv('MuPe-Diversidades.csv') # COMMENT THIS OR THE FOLLOWING
df_complete_mupe_diversidades = pd.read_csv('MuPe-Diversidades_corrigido.csv') # COMMENT THIS OR THE PREVIOUS
df_complete_mupe_diversidades['ID'] = df_complete_mupe_diversidades['stratificationID'].str.split('_').str[0]

# SEPARATING FULL MUPE DIVERSIDADES INTO SPEAKERS, LOCATING CURRENT SPEAKER'S DATAFRAME
dataframes_list = [group for _, group in df_complete_mupe_diversidades.groupby('ID')]
for df in dataframes_list: # ACHO QUE NÃO PRECISA REINDEXAR TODOS OS DFS, SÓ PRECISO LOCALIZAR O CERTO
    df.reset_index(drop=True, inplace=True)
    print(df.at[0, 'ID'], " - length: ", len(df))
    if df.at[0, 'ID'] == csv_path.split('_')[0]:
        df_prosodic_new = df

# ADDING COLUMN SET TO CURRENT SPEAKER'S DATAFRAME
key_columns = ['frame']
df_prosodic = df_prosodic.merge(df_prosodic_new[key_columns + ['set']],on=key_columns,how='left')
df_prosodic['set'] = df_prosodic['set'].fillna('FILTERED') # filtered speakers were not used in training, therefore they can be colored for evaluation - maybe even a different color...
#print(df_prosodic)

# Predicting boundaries
predicted_labels = chosen_model.predict(X)  

# Generating textgrid according to predicted boundaries
predicted_syllables = df_prosodic['frame']
attributed_set_column = df_prosodic['set']
reference_label_column = df_prosodic['label']

syllables_tier = tg_phone.get_tier_by_name("silabas-fonemas")
phrase_phonemes_tier = tg_phone.get_tier_by_name("frase-fonemas")
phrase_graphemes_tier = tg_phone.get_tier_by_name("frase-grafemas")
syllables_tier = [syllable for syllable in syllables_tier if syllable.text != "sil"] # removing silences

# CREATING FINAL TEXTGRID TIERS
final_textgrid = tgt.core.TextGrid()
new_tier = tgt.core.IntervalTier(start_time=0, end_time=predicted_syllables[len(predicted_syllables)-1].split('_')[3], name="Prosodic Segmented Units", objects=None)
new_syllable_tier = tgt.core.IntervalTier(start_time=0, end_time=predicted_syllables[len(predicted_syllables)-1].split('_')[3], name="Syllables", objects=None)

phrase_phonemes_list = phrase_phonemes_tier[0].text.split()
phrase_graphemes_list = phrase_graphemes_tier[0].text.split()

i = 0
interval_start_time = 0
interval_text = ""
words_list_index = 0
current_word = ""
csv_syllable_end_time = 0

if(len(syllables_tier) != len(predicted_syllables)):
    print("Quantity of syllables of the csv file and quantity of syllables of phonemes textgrid file are different. Can't continue. Killing program.")
    print("Len syllables tier:", len(syllables_tier))
    print("Len predicted syllables:", len(predicted_syllables))

for i in range(len(predicted_syllables)):

    csv_syllable_text = predicted_syllables[i].split('_')[1]
    csv_syllable_text_aux = csv_syllable_text

    # CRIANDO INTERVALO COLORIDO DA CAMADA DE SÍLABAS
    syl_attributed_set = attributed_set_column[i]
    last_syllable_end_time = csv_syllable_end_time
    csv_syllable_end_time = float(predicted_syllables[i].split('_')[3])
    csv_syllable_start_time = float(predicted_syllables[i].split('_')[2])

    # ADICIONA SILÊNCIO SE PRECISAR
    if last_syllable_end_time != csv_syllable_start_time: 
        new_syllable_interval = tgt.core.Interval(start_time=last_syllable_end_time,end_time=csv_syllable_start_time, text="sil")
        new_syllable_tier.add_interval(new_syllable_interval)

    if syl_attributed_set == 'TEST SET':
        csv_syllable_text_aux = csv_syllable_text_aux+" TEST SET"
    elif syl_attributed_set == 'FILTERED':
        csv_syllable_text_aux = csv_syllable_text_aux+" FILTERED"
    else:
        csv_syllable_text_aux = csv_syllable_text_aux+" TRAIN SET"
    
    if reference_label_column[i] == predicted_labels[i]:
        csv_syllable_text_aux = csv_syllable_text_aux+" ACERTO - "+predicted_labels[i]
    else:
        csv_syllable_text_aux = csv_syllable_text_aux+" ERRO - "+predicted_labels[i]
        print(predicted_syllables[i]," ERRO: predicted-", predicted_labels[i], " reference-", reference_label_column[i])

    new_syllable_interval = tgt.core.Interval(start_time=csv_syllable_start_time,end_time=csv_syllable_end_time, text=csv_syllable_text_aux)
    new_syllable_tier.add_interval(new_syllable_interval)

    # CRIANDO INTERVALO DA CAMADA DE UNIDADES ENTOACIONAIS
    # Adiciono a sílaba atual
    current_word += csv_syllable_text

    # Comparo com a camada de 
    if current_word == phrase_phonemes_list[words_list_index]: # se chegou ao fim de uma palavra, adiciono espaço
        if interval_text != "":
            interval_text += " "
        interval_text += phrase_graphemes_list[words_list_index]
        words_list_index += 1
        current_word = ""
    else: # SERIA O IDEAL - VER COM SANDRA SE A GENTE COLOCA ESSA BARREIRA DE NUNCA SEGMENTAR NO MEIO DE PALAVRAS, OU SE A GENTE SEGMENTA IGUALZINHO O ALGORITMO DE ML QUER
        if predicted_labels[i] == 'TB':
            print("Algoritmo previu uma fronteira no meio de uma palavra, estou barrando e seguindo sem marcá-la:", predicted_syllables[i])
        continue

    if predicted_labels[i] == 'TB' or i == len(predicted_syllables)-1: #se chegou à uma fronteira prosódica prevista, cria-se um intervalo de texto
        csv_syllable_end_time = float(predicted_syllables[i].split('_')[3])
        new_interval = tgt.core.Interval(start_time=interval_start_time,end_time=csv_syllable_end_time, text=interval_text)
        new_tier.add_interval(new_interval)
        
        # checking if we need a silence interval after the current interval
        if i+1 < len(predicted_syllables) and csv_syllable_end_time != float(predicted_syllables[i+1].split('_')[2]):
            new_interval = tgt.core.Interval(start_time=csv_syllable_end_time,end_time=float(predicted_syllables[i+1].split('_')[2]), text="sil") # Here, should I write "sil" instead?
            new_tier.add_interval(new_interval)
            interval_start_time = float(predicted_syllables[i+1].split('_')[2])
        else:
            interval_start_time = csv_syllable_end_time
        interval_text = ""
        
    elif predicted_labels[i] == 'NB':
        continue
    else:
        print("ERROR, NO LABEL WAS ASSIGNED TO CURRENT SYLLABLE, ENDING PROGRAM")
        quit()
    
final_textgrid.add_tier(new_syllable_tier)
final_textgrid.add_tier(new_tier)

reference_tier_names = tg_reference.get_tier_names()
for name in reference_tier_names:
    new_reference_tier = tg_reference.get_tier_by_name(name)
    final_textgrid.add_tier(new_reference_tier)

tgt.io.write_to_file(final_textgrid, final_tg_name, format='long', encoding='utf-8') 

print("\nTextgrid with prosodic segmented utterances generated successfully!")
print("It can be found in the same folder of this code with the name:",final_tg_name)