import sys
import re
import os

clean_vocab ='ABCDEFGHIJKLMNOPQRSTUVWXYZÇÃÀÁÂÊÉÍÓÔÕÚÛabcdefghijklmnopqrstuvwxyzçãàáâêéíóôõúû\-\'\n\ '

def clean_text(new_text):
    if len(new_text) > 0 and new_text[0] == ' ':
        new_text = new_text[1:]

    # Substitui caracter proibido "ũ" por "um"
    new_text = re.sub("ũ", "um", new_text)

    # Remove texto entre parênteses duplos
    new_text = re.sub("\(\([^)]*\)\)", "", new_text)

    # Remove texto entre parênteses duplos
    new_text = re.sub("\*[^)]*\:", "", new_text)

    # Remove texto entre parênteses duplos e "..." (caso o transcritor tenha esquecido de fechar os parênteses)
    new_text = re.sub("\(\([^(\.\.\.)]*\.\.\.", "", new_text)

    # Troca :: por espaço (pode causar erro quebrando palavras ou não. ex: "eh::assim" ou "u::ma pessoa")
    new_text = re.sub("::", " ", new_text)

    # Troca / por espaço
    new_text = re.sub("/", "", new_text)
    
    # Troca - por espaço
    new_text = re.sub("-", " ", new_text)

    # Troca ` por '
    new_text = new_text.replace("`","'")

    # se não há texto, só pontuação, retornamos a string vazia ""
    if not re.search('[A-Za-z0-9áàâãéèêíóôõúçÁÀÂÃÉÈÍÓÔÕÚÇ]', new_text):
        return ""

    # Formata conforme o vocabulário limpo
    new_text = re.sub("[^{}]".format(clean_vocab), "", new_text)

    # Remove múltiplos espaços
    new_text = re.sub("[ ]+", " ", new_text)

    new_text = re.sub("(?<![A-Z])\.", "", new_text)
    new_text = re.sub("\n[ ]+", "\n", new_text)
    new_text = re.sub("\n{3, 6}", "\n\n", new_text)
    new_text = re.sub("[ ]+", " ", new_text)

    # Substitui ehhhhhh por eh e afins
    new_text = re.sub("h+", "h", new_text)

    new_text = re.sub("'", "", new_text)

    new_text = re.sub(' +', ' ', new_text)
    new_text = new_text.replace("\n ", "\n")

    new_text = new_text.lower()

    if len(new_text.split("\n")) > 0:
        new_text = os.linesep.join([s for s in new_text.splitlines() if s])
    return new_text

if len(sys.argv) < 2:
    print("Missing textgrid filename, please write it like this when you run the code: python3 mycode.py mytextgrid.TextGrid")
    sys.exit(1)
  # Adapt here according to the path of your audio and textgrid generated by ufpalign
txt_name = sys.argv[1]
final_txt_name = txt_name.split('.')[0] + "_clean_text.txt"

reference_file = open(txt_name, "r")

content = reference_file.read()
content = clean_text(content)

reference_file.close()
print(content)

f1 = open(final_txt_name, "w")
f1.write(content)
f1.close()