import sys
import tgt
import chardet
import pandas

def attributing_labels(syllables_tier, all_utterances):
  labels = []
  i_utt = 0
  #(Going through syllables tier, verifying whether each syllable's start time is smaller than the end time of the current utterance, meaning that the current syllable would belong to the current utterance, and label "NB" (no boundary) is attributed. If not, "TB" is attributed and we move to the next syllable and utterance)
  for i_syl, syllable in enumerate(syllables_tier): 
    if syllable.text != "sil":
      if i_utt >= len(all_utterances):
        labels.append("NB")
      elif  i_syl+1 >= len(syllables_tier) or syllables_tier[i_syl+1].start_time >= round(all_utterances[i_utt].end_time, 2):
        labels.append("TB")
        i_utt += 1
      elif syllables_tier[i_syl+1].text == "sil" and syllables_tier[i_syl+1].end_time >= round(all_utterances[i_utt].end_time, 2):
        labels.append("TB")
        i_utt += 1
      elif syllables_tier[i_syl+1].text == "sil" and i_syl+2 < len(syllables_tier) and syllables_tier[i_syl+2].start_time >= round(all_utterances[i_utt].end_time, 2):
        labels.append("TB")
        i_utt += 1
      else:
        labels.append("NB")  
  return labels

def predict_encoding(tg_path):
    '''Predict a file's encoding using chardet'''
    # Open the file as binary data
    with open(tg_path, 'rb') as f:
        # Join binary lines for specified number of lines
        rawdata = b''.join(f.readlines())
    return chardet.detect(rawdata)['encoding']

def concatenate_textgrids(textgrids_list):
  concatenated_textgrid = tgt.util.concatenate_textgrids(textgrids=textgrids_list, ignore_nonmatching_tiers=True, use_absolute_time=False)
  return concatenated_textgrid

def join_inquiries_in_single_dataset():
    estados = ["AL", "BA", "CE", "ES", "GO", "MG", "MS", "PA", "PB", "PE", "PI", "PR", "RJ", "RO", "RS", "SE", "SP"]
    numeros = ["1", "2"]
    all_X = [] # prosodic features from all syllables of all audios
    y = [] # labels from all syllables of all audios
    frames = []
    all_stratification_ids = []
    for estado in estados:
        for numero in numeros:
            audio_id = estado+numero
            print("Processing",audio_id)
            # Reading csv file with prosodic features  extracted from each syllable of the original audio
            try:
                #df_prosodic = pd.read_csv('ExtractedProsodicFeatures/articleversion_newufpalignversion_filtered/'+audio_id+'_prosodic_features__newufpalignversion_articleversion_filtered_speakers.csv') # DELETE AFTER ALL TESTS
                
                # CHOOSE ONE AND COMMENT THE OTHERS

                # 8 or 9 FEATURES ORIGINAL FEATURE 
                #df_prosodic = pd.read_csv('ExtractedProsodicFeatures/'+audio_id+'_prosodic_features_filtered_speakers.csv')

                # 8 or 9 FEATURES NEW FEATURE NEW UFPALIGN
                #df_prosodic = pd.read_csv('ExtractedProsodicFeaturesNEWUFPALIGNVERSION_newfeature/'+audio_id+'_prosodic_features_filtered_speakers_ufpalignnewversion.csv')
                
                # non filtered files new ufpalign new feature
                df_prosodic = pd.read_csv('ExtractedProsodicFeatures/new_feature_newufpalign_corrigidos/'+audio_id+'_prosodic_features.csv')
                
                current_X = df_prosodic[features] 
                current_X = df_prosodic[features].fillna(0) # Replace NaN values with 0 in X
                current_X = current_X.values.tolist()
                all_X.extend(current_X)
                current_y = df_prosodic.label.to_list() # Label column must be filled with labels, such as "TB", "NB" at .csv file
                y.extend(current_y)
                current_frame = df_prosodic['frame'].to_list() # Label column must be filled with labels, such as "TB", "NB" at .csv file
                frames.extend(current_frame)
                df_prosodic['stratificationID'] = audio_id + "_" + df_prosodic['label'] 
                current_stratification_id = df_prosodic['stratificationID'].to_list()
                all_stratification_ids.extend(current_stratification_id) 
            except:
                print(audio_id, "doesn't exist, skipping to the next one")
                continue

    mupe_diversidades = pd.DataFrame(all_X, columns=features)
    mupe_diversidades["frame"] = frames
    mupe_diversidades["label"] = y
    mupe_diversidades["stratificationID"] = all_stratification_ids

# USED FOR MNIMUM CORPUS, NAMING FILES WE NEEDED
if len(sys.argv) < 4:
    print("\nMissing audio or textgrid filenames, please write them like this when you run the code: python3 mycode.py myreference.TextGrid myfeatures.csv myphones_1.TextGrid myphones_2.TextGrid ...\n")
    sys.exit(1)
  # Adapt here according to the path of your audio and textgrid generated by ufpalign

#X, y, all_stratifications_ids = join_inquiries_in_single_dataset() 

features_csv_files = []
tg_phones_textgrids = []
part_ids = []
print("\nArguments (names of the files recorded):\n")
for arg in sys.argv[1:]:
  print(arg)
  if ".csv" in arg:
    features_csv_files.append(arg) # '234_1_prosodic_features.csv',  '234_2_prosodic_features.csv'
  elif "reference" in arg: # MINIMUM CORPUS and CORAL BRASIL
  #elif "OUTPUT" in arg:
    tg_reference = arg # AL1_reference.TextGrid
    id = arg.split("-")[0].split("/")[1] #Minimum corpus and CORAL BRASIL
    #id = arg.split("_")[0].split("/")[3] # mupe diversidades
  else:
    #part_ids.append(arg.split("_")[3].split(".")[0]) # MINIMUM CORPUS
    tg_phones_textgrids.append(arg) #"234_1_fones.TextGrid", "234_2_fones.TextGrid", ...

tg_phones_textgrids.sort()
features_csv_files.sort()
part_ids.sort()

print("\nCheck if each list is complete and ordered correctly:\n")
print(tg_phones_textgrids,"\n")
print(features_csv_files, "\n")
print(part_ids)
print("Check if the following is really the reference textgrid:\n")
print(tg_reference, "\n")

## ONLY NEEDED FOR SEPARATED VERSION
phones_textgrid_endtimes = []
##
## BOTH
tg_reference = tgt.io.read_textgrid(tg_reference, predict_encoding(tg_reference), include_empty_intervals=False)
i=0
last_end_time = 0
while i < len(tg_phones_textgrids):
  tg_phones_textgrids[i] = tgt.io.read_textgrid(tg_phones_textgrids[i], predict_encoding(tg_phones_textgrids[i]), include_empty_intervals=False)
  ## ONLY NEEDED FOR SEPARATED VERSION - IDENTIFYING WHERE EACH PART ENDED WITH UFPALIGN TO SEPARATE THEM FURTHER ON
  #phones_textgrid_endtimes.append(last_end_time+tg_phones_textgrids[i].end_time)
  #if i > 1: # ONLY FOR 360
    #last_end_time += 323.227 # ONLY FOR 360

  phones_textgrid_endtimes.append(last_end_time+tg_phones_textgrids[i].end_time) 
  last_end_time = phones_textgrid_endtimes[i]
  i += 1
  ##
#phones_textgrid_endtimes.extend([1082.01907])  # ONLY FOR D2 360
#phones_textgrid_endtimes.sort() # ONLY FOR D2 360 
#print(phones_textgrid_endtimes)

# CHOOSE ONE OF THE FOLLOWING
TB_tiers = [tier for tier in tg_reference.tiers if tier.name.startswith("TB")] # CORAL BRASIL
#TB_tiers = [tier for tier in tg_reference.tiers if tier.name.startswith("TB-") and "ponto" not in tier.name] # mupe diversidade
#TB_tiers = [tier for tier in tg_reference.tiers if tier.name.startswith("TB-") and "normal" in tier.name] #minimum corpus

if len(TB_tiers) == 0:
  print("ERROR, THERE ARE NO NORMALIZED TIERS IN THE CURRENT TEXTGRID\n\n")
  quit()

all_utterances = []
for tier in TB_tiers:
  all_utterances.extend(tier.intervals)
all_utterances.sort(key=lambda interval: interval.start_time) # list of all utterances, ordered according to start time

################
# SEPARATED VERSION

# Separating reference file into correspondent parts separated to run UFPAlign
reference_parts = []
last_end_time = 0
## TO CREATE REFERENCE TEXTGRIDS SEPARATED IN PARTS
#partial_textgrids = []
####
for index,end_time in enumerate(phones_textgrid_endtimes):
  reference_part = [interval for interval in all_utterances if interval.start_time <= end_time and interval.start_time >= last_end_time]
  reference_parts.append(reference_part)
  if index != 0:
    general_start_time_difference = reference_part[0].start_time
  else:
    general_start_time_difference = 0
  last_end_time = end_time
  ## TO CREATE REFERENCE TEXTGRIDS SEPARATED IN PARTS
  #partial_textgrid = tgt.core.TextGrid()
  #new_tier = tgt.core.IntervalTier(start_time=0, end_time=end_time - general_start_time_difference, name="All TBs-normal", objects=None)
  ####
  for interval in reference_part:
    # correcting start times - to start a textgrid always from 0 
    interval.start_time = interval.start_time - general_start_time_difference
    interval.end_time = interval.end_time - general_start_time_difference
  ## TO CREATE REFERENCE TEXTGRIDS SEPARATED IN PARTS
    #try:
    #  new_tier.add_interval(interval)
    #except:
    #  print("Couldn't add the following interval due to overlap: ", interval,"\n") 
  #partial_textgrid.add_tier(new_tier)
  #partial_textgrids.append(partial_textgrid)
  #######
## TO CREATE REFERENCE TEXTGRIDS SEPARATED IN PARTS
#for index, textgrid in enumerate(partial_textgrids):
#  tgt.io.write_to_file(textgrid,id+"_reference_part"+str(index)+".TextGrid", format='long', encoding='utf-8') 
######

#reference_parts.pop(2) # ONLY FOR D2 360 
if part_ids == []:
  part_ids = ""
i = 0
for csv, phones_textgrid, reference_textgrid in zip(features_csv_files,tg_phones_textgrids,reference_parts):
  syllables_tier = phones_textgrid.get_tier_by_name("silabas-fonemas")
  print("Part ", i+1, " out of ", len(features_csv_files),":\n")
  print("Partial features csv file:\n")
  print(csv,"\n")
  print("Partial reference textgrid beginning and ending:\n")
  print(reference_textgrid[0], reference_textgrid[1], reference_textgrid[2], "[...]", reference_textgrid[-3], reference_textgrid[-2], reference_textgrid[-1],"\n")
  print("Partial corresponding syllables tier beginning and ending:\n")
  print(syllables_tier[0], syllables_tier[1], syllables_tier[2], "[...]", syllables_tier[-3], syllables_tier[-2], syllables_tier[-1],"\n")
  labels = attributing_labels(syllables_tier, reference_textgrid)
  df_prosodic = pandas.read_csv(csv)
  print(labels, len(labels))
  print(df_prosodic['label'], len(df_prosodic['label']))
  print(df_prosodic)
  print(part_ids)
  df_prosodic['label'] = labels
  if part_ids == "":
    df_prosodic.to_csv(id+"_features_labeled.csv", index=False)
    print("The file was named as: ",id+"_features_labeled.csv\n")
  else:
    print("The file was named as: ",id+"_"+part_ids[i]+"_features_labeled.csv\n")
    df_prosodic.to_csv(id+"_"+part_ids[i]+"_features_labeled.csv", index=False)
  print("Features CSV with labels created successfully! Here is a preview:\n")
  print(df_prosodic,"\n")
  
  i += 1

###############################


# CONCATENATED VERSION
#df_prosodic = pandas.concat(map(pandas.read_csv, features_csv_files), ignore_index=True)
#print("Check if the features table was concatenated correctly (starting and ending as it should):\n")
#print(df_prosodic,"\n")
#tg_phone = concatenate_textgrids(tg_phones_textgrids) # concatenated

#tgt.io.write_to_file(tg_phone, id+"_phones_concatenated.TextGrid", format='long', encoding='utf-8')

#syllables_tier = tg_phone.get_tier_by_name("silabas-fonemas")

#labels = attributing_labels(syllables_tier, all_utterances)
#print(labels,"\n")
#df_prosodic = pandas.read_csv(csv_path)
#df_prosodic['label'] = labels
#print(df_prosodic,"\n")
#df_prosodic.to_csv(id+"_features_concatenated_labeled.csv", index=False)